### PR TITLE
fix loop forever

### PR DESCRIPTION
**Pull request by cossonleo**
fix compile error and loop forever when use `?` in main fn

### CODE REVIEW

**Comment by aellwein** [comment]
Thanks! Good catch.

**Comment by aellwein** [comment]
Interestingly, i get a compile error now:
```
error[E0308]: mismatched types
   --> src/lib.rs:149:31
    |
149 |         match Mode::from_bits(umask as u32) {
    |                               ^^^^^^^^^^^^ expected `u16`, found `u32`
    |
help: you can convert a `u32` to a `u16` and panic if the converted value doesn't fit
    |
149 |         match Mode::from_bits((umask as u32).try_into().unwrap()) {
    |                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

```

After looking the code in ``nix::libc``, the type is actually specified as ``mode_t``.
Can we go for  ``match Mode::from_bits((umask as mode_t)`` then? 
For me, it compiles with Rust (1.51.0).

**Comment by aellwein** [comment]
Ok, i've tested the build with GitHub actions and Ubuntu, seems that ``mode_t`` is also working on Linux. Hence i would push this change to master and release the crate.

**Comment by aellwein** [comment]
@cossonleo  daemonizr-0.1.3 is released now.
